-- File: blinky.vhd
-- Generated by MyHDL 0.11
-- Date: Fri Dec 11 22:03:19 2020


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_011.all;

entity blinky is
    port (
        clk_i: in std_logic;
        led_o: out std_logic
    );
end entity blinky;


architecture MyHDL of blinky is



signal cnt: unsigned(23 downto 0);
signal tgl: std_logic;

begin




BLINKY_TOGGLE_LED: process (clk_i) is
begin
    if rising_edge(clk_i) then
        if (signed(resize(cnt, 25)) = (12000000 - 1)) then
            tgl <= (not tgl);
            led_o <= tgl;
            cnt <= to_unsigned(0, 24);
        else
            cnt <= (cnt + 1);
        end if;
    end if;
end process BLINKY_TOGGLE_LED;

end architecture MyHDL;
